/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesWordFindRouteImport } from './routes/games.word-find'
import { Route as GamesQuizRouteImport } from './routes/games.quiz'
import { Route as GamesMemoryRouteImport } from './routes/games.memory'
import { Route as GamesMelodyRouteImport } from './routes/games.melody'
import { Route as GamesMathPuzzleRouteImport } from './routes/games.math-puzzle'
import { Route as GamesMathRouteImport } from './routes/games.math'
import { Route as GamesLetterRaceRouteImport } from './routes/games.letter-race'
import { Route as GamesDrawingRouteImport } from './routes/games.drawing'
import { Route as GamesAnimalsRouteImport } from './routes/games.animals'
import { Route as GamesAlphabetRouteImport } from './routes/games.alphabet'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordFindRoute = GamesWordFindRouteImport.update({
  id: '/games/word-find',
  path: '/games/word-find',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuizRoute = GamesQuizRouteImport.update({
  id: '/games/quiz',
  path: '/games/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/games/memory',
  path: '/games/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMelodyRoute = GamesMelodyRouteImport.update({
  id: '/games/melody',
  path: '/games/melody',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMathPuzzleRoute = GamesMathPuzzleRouteImport.update({
  id: '/games/math-puzzle',
  path: '/games/math-puzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMathRoute = GamesMathRouteImport.update({
  id: '/games/math',
  path: '/games/math',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLetterRaceRoute = GamesLetterRaceRouteImport.update({
  id: '/games/letter-race',
  path: '/games/letter-race',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDrawingRoute = GamesDrawingRouteImport.update({
  id: '/games/drawing',
  path: '/games/drawing',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAnimalsRoute = GamesAnimalsRouteImport.update({
  id: '/games/animals',
  path: '/games/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAlphabetRoute = GamesAlphabetRouteImport.update({
  id: '/games/alphabet',
  path: '/games/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/menu': typeof MenuRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/animals': typeof GamesAnimalsRoute
  '/games/drawing': typeof GamesDrawingRoute
  '/games/letter-race': typeof GamesLetterRaceRoute
  '/games/math': typeof GamesMathRoute
  '/games/math-puzzle': typeof GamesMathPuzzleRoute
  '/games/melody': typeof GamesMelodyRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/word-find': typeof GamesWordFindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/menu': typeof MenuRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/animals': typeof GamesAnimalsRoute
  '/games/drawing': typeof GamesDrawingRoute
  '/games/letter-race': typeof GamesLetterRaceRoute
  '/games/math': typeof GamesMathRoute
  '/games/math-puzzle': typeof GamesMathPuzzleRoute
  '/games/melody': typeof GamesMelodyRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/word-find': typeof GamesWordFindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/menu': typeof MenuRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/animals': typeof GamesAnimalsRoute
  '/games/drawing': typeof GamesDrawingRoute
  '/games/letter-race': typeof GamesLetterRaceRoute
  '/games/math': typeof GamesMathRoute
  '/games/math-puzzle': typeof GamesMathPuzzleRoute
  '/games/melody': typeof GamesMelodyRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/word-find': typeof GamesWordFindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lessons'
    | '/menu'
    | '/games/alphabet'
    | '/games/animals'
    | '/games/drawing'
    | '/games/letter-race'
    | '/games/math'
    | '/games/math-puzzle'
    | '/games/melody'
    | '/games/memory'
    | '/games/quiz'
    | '/games/word-find'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lessons'
    | '/menu'
    | '/games/alphabet'
    | '/games/animals'
    | '/games/drawing'
    | '/games/letter-race'
    | '/games/math'
    | '/games/math-puzzle'
    | '/games/melody'
    | '/games/memory'
    | '/games/quiz'
    | '/games/word-find'
  id:
    | '__root__'
    | '/'
    | '/lessons'
    | '/menu'
    | '/games/alphabet'
    | '/games/animals'
    | '/games/drawing'
    | '/games/letter-race'
    | '/games/math'
    | '/games/math-puzzle'
    | '/games/melody'
    | '/games/memory'
    | '/games/quiz'
    | '/games/word-find'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsRoute: typeof LessonsRoute
  MenuRoute: typeof MenuRoute
  GamesAlphabetRoute: typeof GamesAlphabetRoute
  GamesAnimalsRoute: typeof GamesAnimalsRoute
  GamesDrawingRoute: typeof GamesDrawingRoute
  GamesLetterRaceRoute: typeof GamesLetterRaceRoute
  GamesMathRoute: typeof GamesMathRoute
  GamesMathPuzzleRoute: typeof GamesMathPuzzleRoute
  GamesMelodyRoute: typeof GamesMelodyRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesQuizRoute: typeof GamesQuizRoute
  GamesWordFindRoute: typeof GamesWordFindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/word-find': {
      id: '/games/word-find'
      path: '/games/word-find'
      fullPath: '/games/word-find'
      preLoaderRoute: typeof GamesWordFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quiz': {
      id: '/games/quiz'
      path: '/games/quiz'
      fullPath: '/games/quiz'
      preLoaderRoute: typeof GamesQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/games/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/melody': {
      id: '/games/melody'
      path: '/games/melody'
      fullPath: '/games/melody'
      preLoaderRoute: typeof GamesMelodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/math-puzzle': {
      id: '/games/math-puzzle'
      path: '/games/math-puzzle'
      fullPath: '/games/math-puzzle'
      preLoaderRoute: typeof GamesMathPuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/math': {
      id: '/games/math'
      path: '/games/math'
      fullPath: '/games/math'
      preLoaderRoute: typeof GamesMathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/letter-race': {
      id: '/games/letter-race'
      path: '/games/letter-race'
      fullPath: '/games/letter-race'
      preLoaderRoute: typeof GamesLetterRaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/drawing': {
      id: '/games/drawing'
      path: '/games/drawing'
      fullPath: '/games/drawing'
      preLoaderRoute: typeof GamesDrawingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/animals': {
      id: '/games/animals'
      path: '/games/animals'
      fullPath: '/games/animals'
      preLoaderRoute: typeof GamesAnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/alphabet': {
      id: '/games/alphabet'
      path: '/games/alphabet'
      fullPath: '/games/alphabet'
      preLoaderRoute: typeof GamesAlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsRoute: LessonsRoute,
  MenuRoute: MenuRoute,
  GamesAlphabetRoute: GamesAlphabetRoute,
  GamesAnimalsRoute: GamesAnimalsRoute,
  GamesDrawingRoute: GamesDrawingRoute,
  GamesLetterRaceRoute: GamesLetterRaceRoute,
  GamesMathRoute: GamesMathRoute,
  GamesMathPuzzleRoute: GamesMathPuzzleRoute,
  GamesMelodyRoute: GamesMelodyRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesQuizRoute: GamesQuizRoute,
  GamesWordFindRoute: GamesWordFindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
